apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: firstapp-hpa
  namespace: firstapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: firstapp
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50